// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twfszwftjpgqkifhruix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZnN6d2Z0anBncWtpZmhydWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTk2NjMsImV4cCI6MjA3MTk3NTY2M30.hRR9KNdD9tuoUS3obUVjGHawbZ1Fhbx0LYgoaC6cTyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});